spring:
  datasource:
    #another database for tests
    #url: jdbc:{db}://localhost:{port}/{test schema name}
  jpa:
    hibernate:
      ddl-auto: create-drop
#      create-drop
#    show-sql: 'true'
registration:
  send-email: false
